#!/bin/bash

## Setup the vldrive modules on a lion host.
## This script must be called with a full filename (ie not via PATH)
## so that it can find its auxiliary files.

srcdir=${0%/*}

[ -e $srcdir/vldrive.conf ] || {
    echo "Cannot find $srcdir"
    exit 1
}

module=versaapi
version=1.8.2
prefix=
grep -q 'release 7' /etc/redhat-release && {
    version=1.5.0
    prefix=vl_
}

## Patched version with dkms.conf and dkms_build.sh script.
src=/lnfs/lsst/pkgarchive/${module}-${version}_dkms.tar.xz

if [ -r $src ]; then

    [ -e /usr/src/$module-$version ] || tar -C /usr/src -axf $src

    ## TODO skip if already present in dkms status?
    for f in add build install; do
        dkms $f -m $module -v $version && continue
        echo "dkms $f FAILED"
        break
    done
else
    echo "WARNING: skipping dkms for missing $src"
fi


f=/etc/modules-load.d/vldrive.conf
[ -e $f ] || cp $srcdir/${f##*/} $f


## cat /sys/module/vldrive/parameters/FPGA_BASE should return 3200.
f=/etc/modprobe.d/vldrive.conf
[ -e $f ] || cp $srcdir/modprobed-${f##*/} $f


for f in libVL_OSALib.$version.so libcgos.so; do

    f=/usr/local/lib/$f

    [ -e $f ] && continue

    s=/usr/src/$module-$version/${prefix}${f##*/}

    [ -e $s ] || continue

    cp $s $f

    case $f in
        */libVL_OSALib*) : ;;
        *) continue ;;
    esac

    f=${f##*/}
    (
        cd /usr/local/lib
        ln -s $f ${f/$version./}.1
        ln -s $f ${f/$version./}
    )
done


## Set /dev/vldrive: group gpio, mode 660 (default is root 600).
getent group | grep -q ^gpio: || groupadd gpio
groups ccs | grep -q gpio || usermod -a -G gpio ccs

f=/etc/udev/rules.d/99-vldrive.rules
[ -e $f ] || {
    cp $srcdir/${f##*/} $f

    /sbin/udevadm control --reload-rules
    /sbin/udevadm trigger --type=devices --action=change
}


exit 0
