#!/bin/bash

## Setup the canbus module on a lion host.
## This script must be called with a full filename (ie not via PATH)
## so that it can find its auxiliary files.

srcdir=${0%/*}

[ -e $srcdir/canbus.conf ] || {
    echo "Cannot find $srcdir"
    exit 1
}

module=advSocketCAN
version=1.0.1.0

## Patched version with dkms.conf and fixed driver/Makefile.
src=/lnfs/lsst/pkgarchive/${module}_V${version}_dkms.tar.xz

if [ -r $src ]; then

    [ -e /usr/src/$module-$version ] || tar -C /usr/src -axf $src

    module=$(echo $module | tr '[A-Z]' '[a-z]')

    ## TODO skip if already present in dkms status?
    for f in add build install; do
        dkms $f -m $module -v $version && continue
        echo "dkms $f FAILED"
        break
    done
else
    echo "WARNING: skipping dkms for missing $src"
fi


f=/etc/modules-load.d/canbus.conf
[ -e $f ] || cp $srcdir/canbus.conf $f


can_init=/usr/local/libexec/canbus-init

[ -e $can_init ] || {
    cp $srcdir/${can_init##*/} $can_init
    chmod 755 $can_init
}


f=/etc/systemd/system/canbus.service
[ -e $f ] || sed "s|\$can_init|$can_init|" $srcdir/${f##*/}.template > $f

systemctl enable --now canbus || true

exit 0
